export const CARDS = [
  {
    id: "irene-villa",
    name: "Irene Villa",
    version: "Muralla del Sporting",
    team: "Sporting Gijón",
    position: "Portera",
    element: "Montaña",
    image: "../../Hijos Inazuma/pjs/Irene Villa.png",
    kind: "Portera",
    category: "player",
    rarity: "normal",
    role: "defense",
    affinity: "Montaña",
    affinityPrimary: "guard",
    affinityTotal: { guard: 4, text: "Muralla total: gana 4 de defensa adicional." },
    cost: 3,
    attack: 0,
    guard: 6,
    text: "Gana 6 de defensa.",
    tip: "Úsala antes de un gran ataque para obligar al rival a romper tu muralla.",
    quote: "La portería no cae mientras yo siga en pie.",
  },
  {
    id: "jeanne-darc",
    name: "Jeanne d'Arc",
    version: "Defensora de Lyon",
    team: "Olimpique Lyonnais",
    position: "Defensa",
    element: "Fuerza",
    image: "../../Hijos Inazuma/pjs/Jeanne Darc.jpg",
    kind: "Contraataque",
    category: "player",
    rarity: "normal",
    role: "balance",
    affinity: "Fuerza",
    affinityPrimary: "guard",
    affinityTotal: { attack: 2, guard: 2, text: "Contraataque total: +2 de ataque y +2 de defensa." },
    cost: 3,
    attack: 2,
    guard: 4,
    text: "Ataca con 2 y gana 4 de defensa.",
    tip: "Una carta segura para mantener la presión sin dejar desprotegida tu moral.",
    quote: "Defender también es decidir dónde empieza el ataque.",
  },
  {
    id: "shinoa-hiiragi",
    name: "Shinoa Hiiragi",
    version: "Runa Vampírica",
    team: "Espejismo",
    position: "Defensa",
    element: "Sangre",
    image: "../../Hijos Inazuma/pjs/Shinoa Hiiragi.jpg",
    kind: "Control",
    category: "player",
    rarity: "normal",
    role: "weakening",
    affinity: "Sangre",
    affinityPrimary: "attack",
    affinityTotal: { debuff: 2, text: "Runa total: el próximo ataque rival pierde 2 más." },
    cost: 3,
    attack: 2,
    guard: 2,
    debuff: 2,
    text: "Ataca con 2, gana 2 de defensa y reduce en 2 el próximo ataque rival.",
    tip: "Ralentiza al rival justo antes de que pueda responder con su mejor delantero.",
    quote: "Cuando notes el colmillo, ya será demasiado tarde.",
  },
  {
    id: "shiro-harukawa",
    name: "Shiro Harukawa",
    version: "Instinto Asesino",
    team: "Galaxia",
    position: "Mediocentro",
    element: "Neutral",
    image: "../../Hijos Inazuma/pjs/Shiro Takeda.png",
    kind: "Estrategia",
    category: "player",
    rarity: "normal",
    role: "strategy",
    affinity: "Neutral",
    affinityPrimary: "attack",
    affinityTotal: { buff: 2, text: "Instinto total: tu próximo ataque recibe +2 adicional." },
    cost: 3,
    attack: 3,
    guard: 0,
    buff: 3,
    text: "Ataca con 3 y da +3 a tu próximo ataque.",
    tip: "Abre la jugada con Shiro y deja el golpe decisivo para Renzu o Mavuika.",
    quote: "La ejecución perfecta empieza una jugada antes.",
  },
  {
    id: "riko-wingate",
    name: "Riko Wingate",
    version: "Defensa Kitsune",
    team: "Alpino",
    position: "Mediocentro",
    element: "Hielo",
    image: "../../Hijos Inazuma/pjs/Riko Wingate.jpg",
    kind: "Apoyo defensivo",
    category: "player",
    rarity: "normal",
    role: "defense",
    affinity: "Hielo",
    affinityPrimary: "guard",
    affinityTotal: { guard: 3, draw: 1, text: "Kitsune total: +3 de defensa y roba 1 carta." },
    cost: 2,
    attack: 0,
    guard: 3,
    draw: 1,
    text: "Gana 3 de defensa y roba 1 carta.",
    tip: "Protege tu moral sin perder cartas y ayuda a encontrar la siguiente combinación.",
    quote: "La nieve oculta más caminos de los que parece.",
  },
  {
    id: "renzu-ito",
    name: "Renzu Itō",
    version: "Orgullo Ígneo",
    team: "Raimon",
    position: "Delantero",
    element: "Fuego",
    image: "../../Hijos Inazuma/pjs/Renzu Ito.jpg",
    kind: "Ataque combinado",
    category: "player",
    rarity: "normal",
    role: "attack",
    affinity: "Fuego",
    affinityPrimary: "attack",
    affinityTotal: { attack: 3, text: "Orgullo total: +3 de ataque." },
    cost: 3,
    attack: 5,
    guard: 0,
    bonusIfBuff: 2,
    text: "Ataca con 5. Si tenía una potenciación activa, gana 2 de potencia adicional.",
    tip: "Su Orgullo Ígneo recompensa las jugadas preparadas por Shiro o Wang Qing.",
    quote: "Mi fuego siempre arderá por encima del resto.",
  },
  {
    id: "mavuika-heartless",
    name: "Mavuika Heartless",
    version: "Racha Goleadora",
    team: "Universal",
    position: "Delantera",
    element: "Neutral",
    image: "../../Hijos Inazuma/pjs/Mavuika Heartless.jpg",
    kind: "Remate",
    category: "player",
    rarity: "normal",
    role: "attack",
    affinity: "Neutral",
    affinityPrimary: "attack",
    affinityTotal: { attack: 3, text: "Racha total: +3 de ataque." },
    cost: 4,
    attack: 7,
    guard: 0,
    bonusIfNoGuard: 2,
    text: "Ataca con 7. Si el rival no tiene defensa, gana 2 de potencia adicional.",
    tip: "Rompe primero la defensa y deja que Mavuika convierta la ocasión en un golpe final.",
    quote: "Si dejas un hueco, el partido ya está decidido.",
  },
  {
    id: "victor-koga",
    name: "Victor Koga",
    version: "Tiburón Rojo",
    team: "Raimon",
    position: "Delantero",
    element: "Fuego",
    affinity: "Fuego",
    image: "../../Hijos Inazuma/pjs/Victor Koga.jpg",
    kind: "Asalto Impulsivo",
    category: "player",
    rarity: "special",
    role: "attack",
    affinityPrimary: "attack",
    cost: 4,
    attack: 6,
    bonusIfCardPlayedThisTurn: 2,
    affinityTotal: { attack: 3, text: "Tiburón desatado: +3 de ataque." },
    text: "Ataca con 6. Si ya jugaste otra carta este turno, gana +2 de ataque.",
    tip: "Prepara el terreno con una carta barata y deja que Victor cierre una cadena de Fuego.",
    quote: "Cuando el tiburón acelera, ya no existe la vuelta atrás.",
  },
  {
    id: "pan-walker",
    name: "Pan Walker",
    version: "Poder Dorado",
    team: "Future Raimon",
    position: "Delantera",
    element: "Fuego",
    affinity: "Fuego",
    image: "../../Hijos Inazuma/pjs/Pan Walker.jpg",
    kind: "Shunkanido",
    category: "player",
    rarity: "normal",
    role: "strategy",
    affinityPrimary: "attack",
    cost: 3,
    attack: 4,
    draw: 1,
    talent: {
      id: "poder-dorado",
      name: "Poder Dorado",
      text: "Mientras Pan esté en tu descarte, la tercera carta que juegues cada turno recupera 1 de energía.",
    },
    affinityTotal: { draw: 1, energyGain: 1, text: "Impulso dorado: roba 1 y recupera 1 de energía." },
    text: "Ataca con 4 y roba 1 carta.",
    tip: "Su talento convierte las cadenas largas en turnos mucho más flexibles.",
    quote: "¡Todavía puedo ir más rápido!",
  },
  {
    id: "rikuo-nura",
    name: "Rikuo Nura",
    version: "Dragón Ascendente",
    team: "Galaxia",
    position: "Delantero",
    element: "Dragón",
    affinity: "Dragón",
    image: "../../Hijos Inazuma/pjs/Rikuo Mura.jpg",
    kind: "Refuerzo Samurái",
    category: "player",
    rarity: "normal",
    role: "attack",
    affinityPrimary: "attack",
    cost: 3,
    attack: 4,
    bonusIfHasGuard: 2,
    affinityTotal: { attack: 2, guard: 2, text: "Ascenso total: +2 de ataque y +2 de defensa." },
    text: "Ataca con 4. Si tienes defensa al jugarlo, gana +2 de ataque.",
    tip: "Rikuo premia los mazos que construyen una muralla antes de contraatacar.",
    quote: "Un samurái no separa su defensa de su golpe.",
  },
  {
    id: "willow-proude",
    name: "Willow Proude",
    version: "Romeo Celestial",
    team: "Protocolo Omega 4.0",
    position: "Delantero",
    element: "Aire",
    affinity: "Aire",
    image: "../../Hijos Inazuma/pjs/Willow Proude.jpg",
    kind: "Sierra Celestial",
    category: "player",
    rarity: "special",
    role: "attack",
    affinityPrimary: "attack",
    cost: 4,
    attack: 5,
    pierce: 3,
    affinityTotal: { pierce: 3, text: "Corte total: atraviesa 3 puntos más de defensa." },
    text: "Ataca con 5 y hasta 3 de ese ataque atraviesan directamente la defensa.",
    tip: "Úsalo contra rivales que acumulan defensa y creen estar fuera de peligro.",
    quote: "El cielo siempre encuentra una grieta.",
  },
  {
    id: "nalu-tanaka",
    name: "Nalu Tanaka",
    version: "Torpedo de Alta Mar",
    team: "Mary Times Memorial",
    position: "Delantera",
    element: "Agua",
    affinity: "Agua",
    image: "../../Hijos Inazuma/pjs/Nalu Tanaka.jpg",
    kind: "Ola Monstruo",
    category: "player",
    rarity: "normal",
    role: "attack",
    affinityPrimary: "attack",
    cost: 3,
    attack: 4,
    bonusIfAffinityPlayed: ["Agua", "Hielo"],
    affinityComboBonus: 2,
    affinityTotal: { attack: 3, text: "Marea total: +3 de ataque." },
    text: "Ataca con 4. Gana +2 si antes jugaste una carta de Agua o Hielo este turno.",
    tip: "El Hielo también alimenta su oleaje: Riko, Bronya y Fubuki pueden prepararla.",
    quote: "La marea ya ha decidido hacia dónde va el partido.",
  },
  {
    id: "jikan-alonso",
    name: "Jikan Alonso",
    version: "Heredero Temporal",
    team: "Raimon",
    position: "Mediocentro",
    element: "Metal",
    affinity: "Metal",
    image: "../../Hijos Inazuma/pjs/Jikan Alonso.jpg",
    kind: "Hora Final",
    category: "player",
    rarity: "special",
    role: "strategy",
    affinityPrimary: "attack",
    cost: 3,
    attack: 3,
    nextCardDiscount: 1,
    talent: {
      id: "en-punto",
      name: "En Punto",
      text: "Mientras Jikan esté en tu descarte, la primera carta de cada turno que gaste exactamente toda tu energía roba 1 carta.",
    },
    affinityTotal: { nextCardDiscount: 1, text: "Hora exacta: la próxima carta cuesta 1 menos adicional." },
    text: "Ataca con 3. Tu próxima carta cuesta 1 de energía menos.",
    tip: "Calcula el orden: gastar toda la energía con En Punto activo te devuelve una opción.",
    quote: "El segundo exacto siempre está de mi lado.",
  },
  {
    id: "yachiho-azuma",
    name: "Yachiho Azuma",
    version: "Golden Hour",
    team: "Galaxia",
    position: "Mediocentro",
    element: "Bosque",
    affinity: "Bosque",
    image: "../../Hijos Inazuma/pjs/Yachiho Azuma.jpg",
    kind: "Hora Celestial",
    category: "player",
    rarity: "special",
    role: "strategy",
    affinityPrimary: "attack",
    cost: 3,
    attack: 3,
    scout: 2,
    talent: {
      id: "hora-punta",
      name: "Hora Punta",
      text: "Mientras Yachiho esté en tu descarte, la segunda carta que juegues cada turno cuesta 1 de energía menos.",
    },
    affinityTotal: { draw: 1, energyGain: 1, text: "Hora dorada: roba 1 y recupera 1 de energía." },
    text: "Ataca con 3. Mira las 2 primeras cartas del mazo y añade 1 a tu mano.",
    tip: "Hora Punta hace que el orden de las cartas sea tan importante como sus estadísticas.",
    quote: "No llegas tarde: llegas justo cuando yo quería.",
  },
  {
    id: "yokoya-hitoyoshi",
    name: "Yokoya Hitoyoshi",
    version: "Táctico Sombrío",
    team: "Espejismo",
    position: "Mediocentro",
    element: "Sombra",
    affinity: "Sombra",
    image: "../../Hijos Inazuma/pjs/Yokoya Hitoyoshi.jpg",
    kind: "Luna de Sangre",
    category: "player",
    rarity: "special",
    role: "weakening",
    affinityPrimary: "attack",
    cost: 3,
    attack: 3,
    debuff: 3,
    drawIfDiscardContains: "shinoa-hiiragi",
    affinityTotal: { debuff: 2, text: "Eclipse total: el próximo ataque rival pierde 2 más." },
    text: "Ataca con 3 y reduce en 3 el próximo ataque rival. Si Shinoa está en tu descarte, roba 1.",
    tip: "Yokoya y Shinoa convierten el descarte en una pieza real de tu estrategia.",
    quote: "La sombra correcta puede dirigir todo el campo.",
  },
  {
    id: "natsu-dragneel",
    name: "Natsu Dragneel",
    version: "Corazón de Ultramegahiedra",
    team: "Ultramegahiedra",
    position: "Mediocentro",
    element: "Fuego",
    affinity: "Fuego",
    image: "../../Hijos Inazuma/pjs/Natsu Dragneel.jpg",
    kind: "Impulso Ígneo",
    category: "player",
    rarity: "normal",
    role: "strategy",
    affinityPrimary: "attack",
    cost: 2,
    attack: 2,
    buff: 2,
    affinityTotal: { nextAffinityDiscount: 2, text: "Llama total: la próxima carta de Fuego cuesta 2 menos." },
    text: "Ataca con 2 y da +2 a tu próximo ataque.",
    tip: "Es el inicio barato perfecto para cadenas con Pan, Renzu o Victor.",
    quote: "¡Ahora sí que me he encendido!",
  },
  {
    id: "lambda-zinaida",
    name: "Lambda Zinaida",
    version: "Vector de Galaxia",
    team: "Galaxia",
    position: "Defensa",
    element: "Metal",
    affinity: "Metal",
    image: "../../Hijos Inazuma/pjs/Lambda.jpg",
    kind: "Interferencia Lambda",
    category: "player",
    rarity: "normal",
    role: "balance",
    affinityPrimary: "guard",
    cost: 3,
    attack: 3,
    guard: 3,
    removeOpponentBuff: true,
    affinityTotal: { attack: 2, guard: 2, text: "Vector total: +2 de ataque y +2 de defensa." },
    text: "Ataca con 3, gana 3 de defensa y elimina la potenciación de ataque rival.",
    tip: "Espera a que el rival prepare su remate y corta la jugada antes de que llegue.",
    quote: "Tu trayectoria era predecible.",
  },
  {
    id: "shinbad-ramirez",
    name: "Shinbad Ramírez",
    version: "Guardián de Valefor",
    team: "Raimon",
    position: "Defensa",
    element: "Fuerza",
    affinity: "Fuerza",
    image: "../../Hijos Inazuma/pjs/Shinbad Ramirez.jpg",
    kind: "Fuerza de Tiro",
    category: "player",
    rarity: "special",
    role: "balance",
    affinityPrimary: "guard",
    cost: 3,
    attack: 2,
    guard: 3,
    buff: 1,
    talent: {
      id: "fuerza-de-tiro",
      name: "Fuerza de Tiro",
      text: "Mientras Shinbad esté en tu descarte, tu primera carta ofensiva de cada turno gana +1 de ataque.",
    },
    affinityTotal: { buff: 2, text: "Valefor total: tu próximo ataque recibe +2 adicional." },
    text: "Ataca con 2, gana 3 de defensa y da +1 a tu próximo ataque.",
    tip: "Su talento mejora cada inicio ofensivo sin obligarte a repetir una combinación concreta.",
    quote: "Primero resisto. Después decido dónde golpeamos.",
  },
  {
    id: "bronya-wingate",
    name: "Bronya Wingate",
    version: "Viento Fresco de Hokkaido",
    team: "Instituto Alpino",
    position: "Defensa",
    element: "Hielo",
    affinity: "Hielo",
    image: "../../Hijos Inazuma/pjs/Bronya Wingate.jpg",
    kind: "Kitsunes de Nieve",
    category: "player",
    rarity: "special",
    role: "defense",
    affinityPrimary: "guard",
    cost: 3,
    guard: 5,
    drawIfDiscardContains: "riko-wingate",
    talent: {
      id: "defensa-plus",
      name: "Defensa+",
      text: "Mientras Bronya esté en tu descarte, la primera carta defensiva de Agua o Hielo de cada turno gana +1 de defensa.",
    },
    affinityTotal: { guard: 3, debuff: 1, text: "Ventisca total: +3 de defensa y el próximo ataque rival pierde 1." },
    text: "Gana 5 de defensa. Si Riko está en tu descarte, roba 1 carta.",
    tip: "Las dos Wingate se protegen entre sí y alimentan las cadenas de Hielo.",
    quote: "En Hokkaido aprendimos a convertir el frío en refugio.",
  },
  {
    id: "ciro-castaneda",
    name: "Ciro Castañeda",
    version: "Cerrojo del Levante",
    team: "Levante UD",
    position: "Lateral izquierdo",
    element: "Tierra",
    affinity: "Tierra",
    image: "../../Hijos Inazuma/pjs/Ciro Castañeda.webp",
    kind: "Cierre de Banda",
    category: "player",
    rarity: "normal",
    role: "defense",
    affinityPrimary: "guard",
    cost: 2,
    guard: 4,
    affinityTotal: { guard: 3, text: "Cerrojo total: +3 de defensa." },
    text: "Gana 4 de defensa.",
    tip: "Una defensa barata que permite reservar energía para continuar la cadena.",
    quote: "Por mi banda no se pasa dos veces.",
  },
  {
    id: "delta-hervieux",
    name: "Delta Hervieux",
    version: "Cero Absoluto",
    team: "Espejismo",
    position: "Portera",
    element: "Sombra",
    affinity: "Sombra",
    image: "../../Hijos Inazuma/pjs/Delta.jpg",
    kind: "Parada Triangular",
    category: "player",
    rarity: "normal",
    role: "defense",
    affinityPrimary: "guard",
    cost: 4,
    guard: 8,
    affinityTotal: { guard: 4, text: "Cero total: +4 de defensa." },
    text: "Gana 8 de defensa.",
    tip: "Su coste es alto, pero establece una muralla para preparar contraataques de Sombra.",
    quote: "El ángulo estaba cerrado antes de que disparases.",
  },
  {
    id: "fubuki-sumiye",
    name: "Fubuki Sumiye",
    version: "Marea de Forneus",
    team: "Raimon",
    position: "Portera",
    element: "Agua",
    affinity: "Agua",
    image: "../../Hijos Inazuma/pjs/Fubuki Sumiye.jpg",
    kind: "Portero+",
    category: "player",
    rarity: "special",
    role: "defense",
    affinityPrimary: "guard",
    cost: 4,
    guard: 7,
    draw: 1,
    talent: {
      id: "portero-plus",
      name: "Portero+",
      text: "Mientras Fubuki esté en tu descarte, todas tus cartas de portero ganan +1 de defensa.",
    },
    affinityTotal: { guard: 3, draw: 1, text: "Forneus total: +3 de defensa y roba 1 carta." },
    text: "Gana 7 de defensa y roba 1 carta.",
    tip: "Su talento mejora a Irene, Delta y una segunda copia de la propia Fubuki.",
    quote: "El mar siempre vuelve a cubrir la portería.",
  },
  {
    id: "leii-ishikawa",
    name: "Leii Ishikawa",
    version: "Lectura desde la Banda",
    team: "Galaxia",
    position: "Gerente",
    element: "Apoyo",
    image: "../../Hijos Inazuma/pjs/Leii Ishikawa.jpg",
    kind: "Gerente",
    category: "support",
    rarity: "special",
    role: "support",
    cost: 2,
    attack: 0,
    guard: 0,
    scout: 3,
    talent: {
      id: "perspicacia",
      name: "Perspicacia",
      text: "Mientras Leii esté en tu descarte, en un Robo Táctico mira hasta 3 cartas de la función elegida y quédate con 1.",
    },
    text: "Mira las 3 primeras cartas del mazo y añade 1 de ellas a tu mano.",
    tip: "Busca la pieza que falta en tu combinación sin depender del siguiente robo.",
    quote: "Desde aquí puedo ver la jugada completa.",
  },
  {
    id: "mikan-tsumiki",
    name: "Mikan Tsumiki",
    version: "Atención de Emergencia",
    team: "Galaxia",
    position: "Gerente",
    element: "Apoyo",
    image: "../../Hijos Inazuma/pjs/Mikan Tsumiki.jpg",
    kind: "Gerente",
    category: "support",
    rarity: "special",
    role: "support",
    cost: 2,
    attack: 0,
    guard: 0,
    heal: 2,
    criticalHeal: 3,
    criticalHealThreshold: 7,
    cleanse: true,
    text: "Recupera 2 de moral y elimina tu debilitación. Con 7 o menos de moral, recupera 3.",
    tip: "Guárdala para recuperarte y neutralizar una carta de control de Shinoa.",
    quote: "¡P-perdón! Déjame curarte, por favor.",
  },
  {
    id: "wang-qing",
    name: "Wang Qing",
    version: "Impulso del Raimon",
    team: "Raimon",
    position: "Gerente",
    element: "Apoyo",
    image: "../../Hijos Inazuma/pjs/Wang Qing.jpg",
    kind: "Gerente",
    category: "support",
    rarity: "special",
    role: "support",
    cost: 2,
    attack: 0,
    guard: 0,
    energyGain: 1,
    buff: 2,
    text: "Recupera 1 de energía y da +2 a tu próximo ataque.",
    tip: "Permite encadenar otra carta y deja preparado un delantero para rematar.",
    quote: "Todavía nos queda energía para cambiar este partido.",
  },
  {
    id: "miu-iruma",
    name: "Miu Iruma",
    version: "Laboratorio de Jugadas",
    team: "Galaxia",
    position: "Gerente",
    element: "Apoyo",
    image: "../../Hijos Inazuma/pjs/Miu Iruma.jpg",
    kind: "Gerente",
    category: "support",
    rarity: "special",
    role: "support",
    cost: 2,
    draw: 1,
    talent: {
      id: "invencion",
      name: "Invención",
      text: "Mientras Miu esté en tu descarte, una vez por turno puedes cambiar una carta ofensiva por una defensiva, o al revés.",
    },
    text: "Roba 1 carta. Desde el descarte activa Invención.",
    tip: "Convierte una mano desequilibrada en la respuesta que necesitas sin regalar una carta extra.",
    quote: "Si la jugada no existe, la invento.",
  },
  {
    id: "kazuichi-souda-counter",
    name: "Kazuichi Souda",
    version: "Desmontaje de Emergencia",
    team: "Galaxia",
    position: "Mediocentro",
    element: "Metal",
    affinity: "Metal",
    image: "../../Hijos Inazuma/pjs/Kazuichi Souda.jpg",
    kind: "Rompeguardias",
    category: "player",
    rarity: "special",
    role: "attack",
    affinityPrimary: "attack",
    cost: 3,
    attack: 3,
    guardBreak: 4,
    affinityTotal: { guardBreak: 3, text: "Desmontaje total: destruye 3 puntos más de defensa antes de atacar." },
    text: "Destruye hasta 4 de defensa rival y después ataca con 3.",
    tip: "La respuesta directa a las porterías y murallas que acumulan demasiada defensa.",
    quote: "¡Dame un segundo y te desmonto esa defensa pieza a pieza!",
  },
  {
    id: "aika-wingate-counter",
    name: "Aika Wingate",
    version: "Corte del Vendaval",
    team: "Instituto Alpino",
    position: "Defensa",
    element: "Aire",
    affinity: "Aire",
    image: "../../Hijos Inazuma/pjs/Aika Wingate.jpg",
    kind: "Cortacadenas",
    category: "player",
    rarity: "normal",
    role: "balance",
    affinityPrimary: "guard",
    cost: 3,
    attack: 2,
    guard: 3,
    breakAffinity: true,
    affinityTotal: { attack: 2, guard: 2, text: "Vendaval total: +2 de ataque y +2 de defensa." },
    text: "Ataca con 2, gana 3 de defensa y rompe la cadena de afinidad rival.",
    tip: "Entra justo antes de que el rival complete su tercera carta de afinidad.",
    quote: "Una ráfaga basta para desordenar toda la formación.",
  },
  {
    id: "kyoko-kirigiri-counter",
    name: "Kyoko Kirigiri",
    version: "Interferencia Calculada",
    team: "Espejismo",
    position: "Mediocentro",
    element: "Hielo",
    affinity: "Hielo",
    image: "../../Hijos Inazuma/pjs/Kyoko Kirigiri.jpg",
    kind: "Interferencia",
    category: "player",
    rarity: "special",
    role: "weakening",
    affinityPrimary: "attack",
    cost: 2,
    attack: 2,
    drawLock: 1,
    affinityTotal: { debuff: 2, text: "Caso cerrado: el próximo ataque rival pierde 2." },
    text: "Ataca con 2. El próximo robo adicional o búsqueda del rival queda anulada.",
    tip: "Úsala antes de Leii, Yachiho, Code o cualquier turno preparado para robar varias cartas.",
    quote: "Si conozco la pista, también puedo cerrarte el camino.",
  },
  {
    id: "akane-owari-counter",
    name: "Akane Owari",
    version: "Presión sin Descanso",
    team: "Raimon",
    position: "Delantera",
    element: "Fuerza",
    affinity: "Fuerza",
    image: "../../Hijos Inazuma/pjs/Akane Owari.jpg",
    kind: "Anticuración",
    category: "player",
    rarity: "normal",
    role: "attack",
    affinityPrimary: "attack",
    cost: 3,
    attack: 4,
    healingBlock: 1,
    affinityTotal: { attack: 3, text: "Presión total: +3 de ataque." },
    text: "Ataca con 4 y bloquea la próxima recuperación de moral rival.",
    tip: "Obliga al rival a decidir si desperdicia su curación o aguanta la presión.",
    quote: "¡Nada de descansos hasta que acabe el partido!",
  },
  {
    id: "ishigami-senku-counter",
    name: "Ishigami Senku",
    version: "Análisis de Talentos",
    team: "Galaxia",
    position: "Mediocentro",
    element: "Bosque",
    affinity: "Bosque",
    image: "../../Hijos Inazuma/pjs/Ishigami Senku.jpg",
    kind: "Silencio táctico",
    category: "player",
    rarity: "special",
    role: "strategy",
    affinityPrimary: "attack",
    cost: 3,
    attack: 3,
    talentSilence: true,
    affinityTotal: { draw: 1, text: "Hipótesis total: roba 1 carta." },
    text: "Ataca con 3. Los talentos del descarte rival quedan anulados durante su próximo turno.",
    tip: "Corta las combinaciones que dependen de Pan, Fubuki, Leii o Miu antes de que empiecen.",
    quote: "Una vez entiendo el mecanismo, deja de ser una sorpresa.",
  },
  {
    id: "kokichi-oma-counter",
    name: "Kokichi Oma",
    version: "Finta al Banquillo",
    team: "Espejismo",
    position: "Mediocentro",
    element: "Sombra",
    affinity: "Sombra",
    image: "../../Hijos Inazuma/pjs/Kokichi Oma.jpg",
    kind: "Presión al banquillo",
    category: "player",
    rarity: "special",
    role: "weakening",
    affinityPrimary: "attack",
    cost: 3,
    attack: 2,
    guard: 2,
    coachLock: true,
    affinityTotal: { debuff: 2, text: "Engaño total: el próximo ataque rival pierde 2." },
    text: "Ataca con 2, gana 2 de defensa e impide usar al entrenador rival durante su próximo turno.",
    tip: "Guárdalo para retrasar una habilidad decisiva de Xavier, Diamond, Code o Kurumi.",
    quote: "¿Seguro que esa era la orden del entrenador?",
  },
];

export const COACHES = [
  {
    id: "kurumi-tokisaki",
    name: "Kurumi Tokisaki",
    version: "Míster del Tiempo",
    team: "Raimon B",
    image: "../../Hijos Inazuma/pjs/Jugadores !/Kurumi Tokisaki.jpg",
    color: "#e1596d",
    symbol: "XII",
    abilityType: "rewind",
    abilityName: "Zafkiel — Rebobinar",
    abilityText: "Devuelve una carta de tu descarte a tu mano.",
  },
  {
    id: "xavier-foster",
    name: "Xavier Foster",
    version: "Príncipe de las Estrellas",
    team: "Raimon GO",
    image: "../../Hijos Inazuma/pjs/Jugadores !/XavierFoster.webp",
    color: "#ef625c",
    symbol: "✦",
    abilityType: "stellar-buff",
    abilityName: "Astrometralla",
    abilityText: "Tu próximo ataque recibe +4 de potencia.",
  },
  {
    id: "code",
    name: "Code",
    version: "Sombra Decisiva",
    team: "Instituto Alpino",
    image: "../../Hijos Inazuma/pjs/Jugadores !/Code.jpg",
    color: "#b14d62",
    symbol: "忍",
    abilityType: "ninja-scout",
    abilityName: "Lectura Shinobi",
    abilityText: "Mira las 5 primeras cartas del mazo y añade 1 a tu mano.",
  },
  {
    id: "diamond-white",
    name: "Diamond White",
    version: "Saiyan Legendaria",
    team: "Inazuma Japón",
    image: "../../Hijos Inazuma/pjs/Jugadores !/Diamond White.jpg",
    color: "#f2b33d",
    symbol: "爆",
    abilityType: "explosive-drive",
    abilityName: "Impulso Explosivo",
    abilityText: "Recupera 2 de energía y da +2 a tu próximo ataque.",
  },
  {
    id: "waru-walker",
    name: "Waru Walker",
    version: "Control Legendario",
    team: "Inazuma Japón",
    image: "../../Hijos Inazuma/pjs/Jugadores !/Waru Walker.png",
    color: "#bd70ed",
    symbol: "策",
    abilityType: "tactical-control",
    abilityName: "Dominio del Mediocampo",
    abilityText: "Tus 2 próximas cartas cuestan 1 de energía menos.",
  },
  {
    id: "dark-walker",
    name: "Dark Walker",
    version: "Muro Implacable",
    team: "Inazuma Japón",
    image: "../../Hijos Inazuma/pjs/Jugadores !/Dark Walker.png",
    color: "#4b9bf3",
    symbol: "守",
    abilityType: "iron-wall",
    abilityName: "Bloque Sólido",
    abilityText: "Gana 6 de defensa y elimina tu debilitación.",
  },
];

export const COACHES_BY_ID = Object.fromEntries(COACHES.map((coach) => [coach.id, coach]));
export const LEADER = COACHES[0];

export const DECK_SIZE = 12;
export const MAX_COPIES = 2;
export const MIN_UNIQUE_CARDS = 6;
export const MIN_OFFENSIVE_CARDS = 4;
export const MIN_DEFENSIVE_CARDS = 4;

export const STARTER_UNLOCKS = [
  "irene-villa",
  "jeanne-darc",
  "riko-wingate",
  "mavuika-heartless",
  "mikan-tsumiki",
  "wang-qing",
  "renzu-ito",
  "natsu-dragneel",
  "nalu-tanaka",
  "shiro-harukawa",
];

export const STARTER_DECK = [
  "irene-villa",
  "jeanne-darc",
  "jeanne-darc",
  "riko-wingate",
  "mavuika-heartless",
  "mavuika-heartless",
  "renzu-ito",
  "natsu-dragneel",
  "nalu-tanaka",
  "shiro-harukawa",
  "mikan-tsumiki",
  "wang-qing",
];

export const CARDS_BY_ID = Object.fromEntries(CARDS.map((card) => [card.id, card]));
