export const CARDS = [
  {
    id: "mark-base",
    name: "Mark Evans",
    version: "Capitán del Raimon",
    kind: "Guardián",
    cost: 2,
    attack: 0,
    guard: 5,
    text: "Gana 5 de defensa.",
    quote: "¡Mientras protejamos la portería, el partido sigue vivo!",
  },
  {
    id: "axel-base",
    name: "Axel Blaze",
    version: "Delantero de fuego",
    kind: "Ataque",
    cost: 3,
    attack: 5,
    guard: 0,
    text: "Ataca con 5 de potencia.",
    quote: "Un disparo puede cambiarlo todo.",
  },
  {
    id: "jude-base",
    name: "Jude Sharp",
    version: "Estratega imperial",
    kind: "Táctica",
    cost: 2,
    attack: 0,
    guard: 0,
    buff: 3,
    draw: 1,
    text: "Tu próximo ataque gana +3. Roba 1 carta.",
    quote: "El encuentro ya estaba decidido tres jugadas atrás.",
  },
  {
    id: "shawn-base",
    name: "Shawn Froste",
    version: "Lobo de Hakuren",
    kind: "Equilibrio",
    cost: 3,
    attack: 3,
    guard: 3,
    text: "Ataca con 3 y gana 3 de defensa.",
    quote: "El hielo también puede arder.",
  },
  {
    id: "nathan-base",
    name: "Nathan Swift",
    version: "Viento veloz",
    kind: "Ataque",
    cost: 1,
    attack: 2,
    guard: 0,
    text: "Ataca con 2 de potencia.",
    quote: "Cuando me veas, ya habré pasado.",
  },
  {
    id: "caleb-base",
    name: "Caleb Stonewall",
    version: "Provocador",
    kind: "Debilitación",
    cost: 2,
    attack: 1,
    guard: 0,
    debuff: 3,
    text: "Ataca con 1. El próximo ataque rival pierde 3.",
    quote: "¿Eso era todo lo que tenías?",
  },
  {
    id: "xavier-base",
    name: "Xavier Foster",
    version: "Capitán de Génesis",
    kind: "Ataque",
    cost: 4,
    attack: 7,
    guard: 0,
    text: "Ataca con 7 de potencia.",
    quote: "La fuerza se demuestra en el campo.",
  },
  {
    id: "archer-base",
    name: "Archer Hawkins",
    version: "Muralla del equipo",
    kind: "Guardián",
    cost: 2,
    attack: 1,
    guard: 4,
    text: "Ataca con 1 y gana 4 de defensa.",
    quote: "No voy a dejar que pases.",
  },
  {
    id: "mark-awakened",
    name: "Mark Evans",
    version: "Mano Celestial Legendaria",
    kind: "Despertar",
    cost: 4,
    attack: 0,
    guard: 9,
    heal: 2,
    evolutionOf: "mark-base",
    text: "Requiere su versión base. Gana 9 de defensa y recupera 2 de moral.",
    quote: "¡Esta portería representa los sueños de todos!",
  },
  {
    id: "axel-awakened",
    name: "Axel Blaze",
    version: "Tormenta de Fuego",
    kind: "Despertar",
    cost: 5,
    attack: 10,
    guard: 0,
    evolutionOf: "axel-base",
    text: "Requiere su versión base. Ataca con 10 de potencia.",
    quote: "Este es el disparo que supera mis límites.",
  },
  {
    id: "jude-awakened",
    name: "Jude Sharp",
    version: "Comandante Absoluto",
    kind: "Despertar",
    cost: 4,
    attack: 2,
    guard: 0,
    buff: 5,
    draw: 1,
    evolutionOf: "jude-base",
    text: "Requiere su versión base. Ataca con 2, da +5 al próximo ataque y roba 1.",
    quote: "Ahora empieza nuestra verdadera estrategia.",
  },
  {
    id: "shawn-awakened",
    name: "Shawn Froste",
    version: "Ventisca Eterna",
    kind: "Despertar",
    cost: 5,
    attack: 7,
    guard: 5,
    evolutionOf: "shawn-base",
    text: "Requiere su versión base. Ataca con 7 y gana 5 de defensa.",
    quote: "Ya no tengo que elegir entre mis dos mitades.",
  },
];

export const STARTER_DECK = CARDS.map((card) => card.id);

export const CARDS_BY_ID = Object.fromEntries(CARDS.map((card) => [card.id, card]));
