/* Archivo de Makai. Fichas y estados confirmados por el usuario. */
window.MAKAI_DATA = {
  "version": 1,
  "villains": [
    {
      "id": "marionette",
      "name": "Marionette",
      "realName": "Taygeta",
      "title": "Maestra de los Hilos",
      "image": "assets/img/makai/marionette-ficha.png",
      "status": "Muerto",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Centro Comercial de Tsukikage",
      "gift": "Titiritero",
      "description": "Genera hilos rojos que, al tocar a un ser vivo, le permiten manejar su cuerpo. La víctima conserva su mente y su consciencia: el control afecta únicamente a sus movimientos.",
      "activation": "Contacto de los hilos rojos con el cuerpo de un ser vivo.",
      "limits": "No altera la mente ni la consciencia. El alcance, la duración y el número máximo de objetivos no están fijados.",
      "notes": "Consiguió atrapar a Ares con sus hilos. Marionette está muerta.",
      "source": "Diseñar don villano; Nombrar don de recuerdos. Nombre, título y mecánica confirmados por el usuario. No se ha confirmado su afiliación a la Liga. Estado vital confirmado por el usuario el 11 de septiembre de 2026. Nueva ficha visual de Marionette aportada en la misma actualización."
    },
    {
      "id": "villana-recuerdos",
      "name": "Mnemosyne",
      "realName": "Isabella Osa",
      "title": "Rosa del Infierno",
      "image": "assets/img/makai/mnemosyne-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Tsukikage",
      "gift": "Nombre por decidir",
      "description": "Adquiere todos los recuerdos de una persona al clavarle las uñas.",
      "activation": "Clavar sus uñas en la víctima.",
      "limits": "No se ha definido si la víctima pierde sus recuerdos, cuánto dura la adquisición ni cuántas memorias puede conservar.",
      "notes": "«Impronta» y «Engrama» se propusieron como nombres del don, pero no consta una elección definitiva. El nombre de esta ficha es una etiqueta provisional.",
      "source": "Nombrar don de recuerdos. Mecánica descrita por el usuario; nombre y afiliación pendientes. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "zoya",
      "name": "Zoya",
      "realName": "",
      "title": "Jefa de los villanos",
      "image": "assets/img/makai/zoya-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Revancha",
      "description": "Acumula parte de la energía de los golpes recibidos y la devuelve en sus ataques. Cuanta más fuerza recibe, más peligroso se vuelve su contraataque.",
      "activation": "Recibir golpes para acumular energía y devolverla al atacar.",
      "limits": "No evita las heridas. No se especifican la capacidad máxima de acumulación ni el tiempo de conservación.",
      "notes": "Jefa de los villanos, confirmado por el usuario. «Me golpeas hoy… y duele mañana.» «El dolor también es un recurso.»",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Liderazgo de Zoya confirmado expresamente por el usuario. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "arlecchino",
      "name": "Arlecchino",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/arlecchino-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Repetición",
      "description": "Repite un impacto con la misma fuerza hasta cinco segundos después. Puede guardar hasta tres impactos.",
      "activation": "Ejecutar directamente un impacto y repetirlo dentro de los cinco segundos siguientes.",
      "limits": "Solo puede guardar tres impactos. No puede repetir impactos que no haya ejecutado directamente.",
      "notes": "«Todo deja una huella.» «Y yo la hago volver.»",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "querehsha",
      "name": "Querehsha",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/querehsha-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Entumecer",
      "description": "Adormece las zonas que toca. Varios contactos pueden inmovilizar temporalmente una extremidad.",
      "activation": "Tocar directamente la zona del cuerpo que quiere adormecer.",
      "limits": "No afecta a zonas que no haya tocado directamente. No se concreta cuánto dura el entumecimiento.",
      "notes": "«El dolor también puede silenciarse.» «Cuanto más te toco, menos te mueves.»",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "farion",
      "name": "Farion",
      "realName": "Gal",
      "title": "",
      "image": "assets/img/makai/farion-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Alcance",
      "description": "Extiende hasta tres metros el contacto de sus golpes y armas.",
      "activation": "Extender el contacto al golpear o utilizar un arma.",
      "limits": "Alcance máximo de tres metros. No aumenta su fuerza y no puede atravesar obstáculos.",
      "notes": "La ficha identifica a Gal con el nombre Farion. «La distancia también es un arma.» «Llega donde otros no.»",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "yelan",
      "name": "Yelan",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/yelan-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Desfase",
      "description": "Tras cruzar miradas, hace que un objetivo vea y oiga sus movimientos con medio segundo de retraso durante diez segundos.",
      "activation": "Cruzar miradas con el objetivo.",
      "limits": "Retraso de 0,5 segundos durante 10 segundos. La ficha describe el efecto sobre un objetivo.",
      "notes": "El efecto retrasa la percepción visual y auditiva de sus movimientos.",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "jane-doe",
      "name": "Jane Doe",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/jane-doe-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Punto ciego",
      "description": "Cuando alguien la pierde de vista, puede desplazarse hasta cinco metros en un instante.",
      "activation": "Quedar fuera de la vista de quien la observa.",
      "limits": "Necesita un camino libre. No puede activarlo si otra persona la está mirando directamente. Desplazamiento máximo de cinco metros.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "sage",
      "name": "Sage",
      "realName": "",
      "title": "Inteligencia artificial",
      "image": "assets/img/makai/sage-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Inteligencia artificial",
      "description": "Es una inteligencia artificial. La ficha no detalla un don ni capacidades específicas.",
      "activation": "No se especifica en la ficha.",
      "limits": "No se especifican capacidades ni limitaciones en la ficha.",
      "notes": "Inteligencia artificial: esta es su naturaleza, no el nombre de un don confirmado.",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "bete-noire",
      "name": "Bete Noire",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/bete-noire-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Sin don",
      "description": "No posee don, según la ficha proporcionada.",
      "activation": "No aplica: sin don.",
      "limits": "La ficha no describe otras habilidades ni limitaciones.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "goetia",
      "name": "Goetia",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/goetia-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Sin don",
      "description": "No posee don, según la ficha proporcionada.",
      "activation": "No aplica: sin don.",
      "limits": "La ficha no describe otras habilidades ni limitaciones.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "drunken-goddess",
      "name": "Drunken Goddess",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/drunken-goddess-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Bar",
      "description": "Puede crear infinitas bebidas con distintos efectos al ingerirlas.",
      "activation": "Crear las bebidas; sus efectos se producen al ingerirlas.",
      "limits": "No se especifican los efectos concretos, su duración ni restricciones adicionales.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "sweetheart",
      "name": "Sweetheart",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/sweetheart-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Sin don",
      "description": "No posee don, según la ficha proporcionada.",
      "activation": "No aplica: sin don.",
      "limits": "La ficha no describe otras habilidades ni limitaciones.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "kaldea",
      "name": "Kaldea",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/kaldea-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Mirada ígnea",
      "description": "Puede hacer arder todo lo que ve, excepto seres vivos. El fuego sí puede quemar a seres vivos si se propaga hasta ellos.",
      "activation": "Mirar aquello que quiere hacer arder.",
      "limits": "No puede prender directamente a seres vivos con la mirada; pueden sufrir quemaduras por la propagación del fuego.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "demon-human",
      "name": "Demon Human",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/demon-human-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Aislamiento",
      "description": "Al tocar a un rival, reduce su ki y pierde la misma cantidad del suyo. También puede alterar la sensación del ki: benigno o maligno.",
      "activation": "Contacto con un rival para reducir su ki. La activación de la alteración de la sensación del ki no se especifica.",
      "limits": "Pierde exactamente la misma cantidad de ki que reduce al rival. No se especifican duración ni alcance de la alteración de su sensación.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "antiquiles",
      "name": "Antiquiles",
      "realName": "",
      "title": "",
      "image": "assets/img/makai/antiquiles-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sin confirmar",
      "gift": "Cadenas de Aquiles",
      "description": "Al liberarse de sus cadenas, aumenta enormemente sus capacidades físicas y mentales.",
      "activation": "Liberarse de sus cadenas.",
      "limits": "Con las cadenas puestas, sus poderes se reducen, pero no desaparecen. No se especifican duración ni magnitud exacta del aumento.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    },
    {
      "id": "kissara",
      "name": "Kissara",
      "realName": "Capella Emerada",
      "title": "el Labio Sosegado",
      "image": "assets/img/makai/kissara-ficha.png",
      "status": "Vivo",
      "affiliation": "Liga de Villanos",
      "threat": "Sin evaluar",
      "location": "Sede de los Villanos",
      "gift": "Beso Dulce",
      "description": "Al besar a alguien en los labios, aumenta drásticamente su producción de serotonina y endorfinas en contra de su voluntad. Produce una sensación de letargo y relajación máximas, dificultando las actividades que requieran esfuerzo físico. El efecto es acumulativo dependiendo de la cantidad de besos.",
      "activation": "Besar a alguien en los labios.",
      "limits": "La ficha no describe otras habilidades o limitaciones.",
      "notes": "",
      "source": "Ficha visual aportada por el usuario el 11 de septiembre de 2026. Estado vital confirmado por el usuario el 11 de septiembre de 2026."
    }
  ],
  "statusRevision": "20260911-vitales"
};
