/* Datos editables. La interfaz vive en otro archivo. */
window.RP_SERIES = [
      {
        title: "The Promised Neverland",
        poster: "fotos/Yakusoku.jpg",
        status: "Viendo",
        platform: "Animeninja",
        genre: ["Aventura", "Drama"],
        seasons: 2,
        episodes: 23,
        watchedEpisodes: 12,
        year: 2019,
        universe: "Anime",
        ratings: { Y: 8, S: 8.5, L: 9 },
        favorite: true,
        notes: "Emma, Norman y Ray, tres niños superdotados en un orfanato idílico, descubren que su hogar es en realidad una granja de humanos criada para alimentar a monstruos. Al conocer la siniestra verdad, planean escapar junto a sus hermanos para sobrevivir"
      },
      {
        title: "Dragon Ball Z Kai",
        poster: "fotos/dragonballzkai.jpg",
        status: "Viendo",
        platform: "Netflix",
        genre: ["Acción", "Drama", "Shonen"],
        seasons: 2,
        episodes: 169,
        watchedEpisodes: 133,
        year: 2009,
        universe: "Anime",
        ratings: { Y: 9.4, S: 9.5, L: 8 },
        favorite: true,
        notes: "A medida que las fuerzas de los confines del universo descienden sobre la Tierra, Goku y sus aliados son los únicos que se interponen entre la paz y el fin de la humanidad."
      },
      {
        title: "NieR: Autómata",
        poster: "fotos/NieR Automata.webp",
        status: "Viendo",
        platform: "Crunchyroll",
        genre: ["Acción", "Drama", "Shonen", "Postapocalíptico"],
        seasons: 1,
        episodes: 24,
        watchedEpisodes: 7,
        year: 2023,
        universe: "Anime",
        ratings: { Y: 9.4, S: 9, L: 8.5 },
        favorite: true,
        notes: "2B es una unidad que participa en una misión que tristemente sale mal y eliminan a todo su equipo. Ella intenta seguir con su misión, donde conoce a 9S."
      },
      {
        title: "Date a Live",
        poster: "fotos/Datealive.jpg",
        status: "Completa",
        platform: "AnimeFLV",
        genre: ["Acción", "Drama", "Romance", "Fantasía", "Comedia", "Ciencia Ficción"],
        seasons: 5,
        episodes: 58,
        watchedEpisodes: 58,
        year: 2013,
        universe: "Anime",
        ratings: { Y: 9, S: 8.75, L: 9 },
        favorite: true,
        notes: "Shido descubre que los terremotos espaciales son causados por Espíritus, seres peligrosos que amenazan a la humanidad. Para detenerlos, deberá hacer algo inesperado: conquistar sus corazones y lograr que se enamoren de él."
      },
      {
        title: "Chained Soldier",
        poster: "fotos/mato.jpg",
        status: "Completa",
        platform: "Animeninja",
        genre: ["Acción", "Fantasía", "Ecchi"],
        seasons: 2,
        episodes: 24,
        watchedEpisodes: 24,
        year: 2024,
        universe: "Anime",
        ratings: { Y: 9, S: 8.75, L: 9 },
        favorite: true,
        notes: "En un mundo donde portales llamados 'Mato' liberan monstruos y otorgan poderes solo a mujeres, Yuuki Wakura es rescatado por Kyouka Uzen, líder de una unidad especial. A cambio de su ayuda en combate, Yuuki se convierte en su 'esclavo', obteniendo habilidades especiales mientras lucha contra las amenazas de Mato."
      },
      {
        title: "No Game No Life",
        poster: "fotos/NoGameNoLife.webp",
        status: "Completa",
        platform: "Netflix",
        genre: ["Aventura", "Fantasía", "Comedia", "Isekai"],
        seasons: 1,
        episodes: 12,
        watchedEpisodes: 12,
        year: 2014,
        universe: "Anime",
        ratings: { Y: 8.5, S: 8.5, L: 9 },
        favorite: true,
        notes: "Sora y Shiro, dos hermanos prodigio en los juegos conocidos como 'Blank', son transportados a Disboard, un mundo donde todo se decide mediante juegos. Allí deberán enfrentarse a distintas razas y desafíos para alcanzar al dios Tet y conquistar ese mundo basado en reglas absolutas."
      },
      {
        title: "More Than a Married Couple, But Not Lovers",
        poster: "fotos/fuufuijou.jpg",
        status: "Completa",
        platform: "Crunchyroll",
        genre: ["Romance", "Comedia", "Slice of Life"],
        seasons: 1,
        episodes: 12,
        watchedEpisodes: 12,
        year: 2022,
        universe: "Anime",
        ratings: { Y: 8.5, S: 7.5, L: 8.8 },
        favorite: true,
        notes: "Jirou Yakuin y Akari Watanabe son emparejados en una práctica escolar donde deben vivir como si fueran un matrimonio. Aunque ambos tienen interés en otras personas, deberán colaborar para obtener buena puntuación, lo que poco a poco complica sus sentimientos."
      },
      {
        title: "Danganronpa: The Animation",
        poster: "fotos/danganronpa.jpg",
        status: "Completa",
        platform: "AnimeFLV",
        genre: ["Misterio", "Psicológico", "Thriller"],
        seasons: 1,
        episodes: 13,
        watchedEpisodes: 13,
        year: 2013,
        universe: "Anime",
        ratings: { Y: 8.70, S: 8.25, L: 9.5 },
        favorite: true,
        notes: "Makoto Naegi es aceptado en la Academia Hope's Peak, donde estudiantes de élite quedan atrapados por el misterioso oso Monokuma. Para escapar, deberán cometer un asesinato sin ser descubiertos en los juicios escolares, donde la lógica y la deducción decidirán su destino."
      },
      {
        title: "Scarlet Nexus",
        poster: "fotos/scarletnexus.jpg",
        status: "Completa",
        platform: "Crunchyroll",
        genre: ["Acción", "Ciencia ficción"],
        seasons: 1,
        episodes: 26,
        watchedEpisodes: 26,
        year: 2021,
        universe: "Anime",
        ratings: { Y: null, S: 9, L: 9 },
        favorite: true,
        notes: "En un futuro donde extrañas criaturas llamadas 'Others' atacan a la humanidad, un grupo especial con poderes psíquicos lucha para defenderla. Yuito Sumeragi y Kasane Randall se unen a esta fuerza, descubriendo secretos ocultos sobre el mundo y sus propias habilidades."
      },
      {
        title: "The Eminence in Shadow",
        poster: "fotos/eminence.webp",
        status: "Viendo",
        platform: "Netflix",
        genre: ["Acción", "Fantasía", "Comedia", "Isekai"],
        seasons: 2,
        episodes: 32,
        watchedEpisodes: 7,
        year: 2022,
        universe: "Anime",
        ratings: { Y: 8.7, S: 8, L: null },
        favorite: true,
        notes: "Cid Kagenou sueña con convertirse en una figura poderosa que actúe desde las sombras. Tras reencarnarse en un mundo de fantasía, crea la organización Shadow Garden y lucha contra una supuesta conspiración… que resulta ser real, aunque él cree que todo es parte de su propia fantasía."
      },
      {
      title: "Lycoris Recoil",
      poster: "fotos/lycoris.webp",
      status: "Completa",
      platform: "Crunchyroll",
      genre: ["Acción", "Slice of Life"],
      seasons: 1,
      episodes: 13,
      watchedEpisodes: 13,
      year: 2022,
      universe: "Anime",
      ratings: { Y: 9, S: 9.5, L: 9.5 },
      favorite: true,
      notes: "En Japón, una organización secreta emplea a chicas conocidas como 'Lycoris' para prevenir crímenes antes de que ocurran. Chisato Nishikigi y Takina Inoue trabajan en una sucursal encubierta como cafetería, donde combinan misiones con una vida cotidiana aparentemente normal."
    },
    {
      title: "Kill la Kill",
      poster: "fotos/kill la kill.webp",
      status: "Completa",
      platform: "Crunchyroll",
      genre: ["Acción", "Comedia", "Ecchi"],
      seasons: 1,
      episodes: 24,
      watchedEpisodes: 24,
      year: 2013,
      universe: "Anime",
      ratings: { Y: 8.75, S: 9, L: 10 },
      favorite: true,
      notes: "Ryuko Matoi llega a la Academia Honnouji en busca del asesino de su padre. Armada con una espada tijera y acompañada por el uniforme viviente Senketsu, desafía a la presidenta del consejo estudiantil Satsuki Kiryuin y su sistema basado en el poder de los uniformes especiales."
    },
    {
      title: "Shikimori's not Just a Cutie",
      poster: "fotos/shikimori.webp",
      status: "Completa",
      platform: "Crunchyroll",
      genre: ["Romance", "Comedia", "Slice of Life"],
      seasons: 1,
      episodes: 12,
      watchedEpisodes: 12,
      year: 2022,
      universe: "Anime",
      ratings: { Y: 8, S: 8, L: null },
      favorite: true,
      notes: "Izumi, un chico con una racha constante de mala suerte, sale con Shikimori, una chica aparentemente adorable que también muestra un lado cool y protector cuando él está en peligro. Su relación combina momentos cotidianos con situaciones donde Shikimori demuestra su carácter fuerte."
    },
    {
      title: "The 100 Girlfriends who Really, Really, Really, Really, REALLY love you",
      poster: "fotos/100novias.webp",
      status: "En emisión",
      platform: "Crunchyroll",
      genre: ["Comedia", "Romance", "Harem"],
      seasons: 1,
      episodes: 12,
      watchedEpisodes: 4,
      year: 2023,
      universe: "Anime",
      ratings: { Y: 9, S: null, L: 7 },
      favorite: true,
      notes: "Rentarou Aijou descubre que está destinado a tener 100 almas gemelas. Sin embargo, si no corresponde adecuadamente a cada una de ellas, sufrirán graves consecuencias, por lo que deberá hacer todo lo posible para amar a todas por igual."
    },
    {
      title: "Cyberpunk: Edgerunners",
      poster: "fotos/edgerruners.jpg",
      status: "Completa",
      platform: "Netflix",
      genre: ["Acción", "Ciencia ficción"],
      seasons: 1,
      episodes: 10,
      watchedEpisodes: 10,
      year: 2022,
      universe: "Anime",
      ratings: { Y: 9.5, S: 9.5, L: 9.8 },
      favorite: true,
      notes: "En Night City, una metrópolis obsesionada con la tecnología y las modificaciones corporales, David Martinez decide convertirse en un edgerunner, un mercenario fuera de la ley, tras una tragedia personal que cambia su vida."
    },
    {
      title: "Arknights: Reimei Zensou",
      poster: "fotos/arknights.jpg",
      status: "Pausada",
      platform: "Crunchyroll",
      genre: ["Acción", "Fantasía", "Ciencia ficción"],
      seasons: 2,
      episodes: 16,
      watchedEpisodes: 8,
      year: 2022,
      universe: "Anime",
      ratings: { Y: 8, S: 8, L: 7.5 },
      favorite: false,
      notes: "En un mundo devastado por catástrofes y una enfermedad incurable, la organización Rhodes Island lucha por encontrar una cura mientras combate conflictos políticos y militares. El Doctor, un estratega clave, lidera operaciones contra diversas amenazas."
    },
    {
        title: "We Never Learn",
        poster: "fotos/We Never Learn.jpg",
        status: "Completa",
        platform: "AnimeFLV",
        genre: ["Comedia", "Romance", "Slice of Life"],
        seasons: 2,
        episodes: 26,
        watchedEpisodes: 26,
        year: 2019,
        universe: "Anime",
        ratings: { Y: 8.8, S: null, L: 8.7
        },
        favorite: true,
        notes: "Nariyuki Yuiga, un estudiante promedio, se ve obligado a convertirse en tutor de tres genios femeninas para asegurar su ingreso a la universidad. A medida que las ayuda a superar sus dificultades académicas, surgen complicaciones románticas y cómicas entre ellos."
      },
    ];
