name: Avisar actualización web

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar aviso a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg commit "$COMMIT_MESSAGE" \
            '{
              "content":"<@&1514803118746108004>",
              "embeds":[
                {
                  "title":"🌐 Nueva actualización de la web",
                  "description":$commit,
                  "color":3447003,
                  "fields":[
                    {
                      "name":"🔗 Enlace",
                      "value":"https://yisusschrist.github.io/Web-Rol/"
                    }
                  ],
                  "footer":{
                    "text":"Web-Rol"
                  },
                  "timestamp":now|strftime("%Y-%m-%dT%H:%M:%SZ")
                }
              ]
            }')

          curl \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "$DISCORD_WEBHOOK"