name: Avisar actualización web

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar aviso a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg content "📢 <@&1514803118746108004>
          🌐 **Nueva actualización de la web**

          📝 Último cambio:
          $COMMIT_MESSAGE

          🔗 https://yisusschrist.github.io/Web-Rol/" \
            '{content: $content}')

          curl -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "$DISCORD_WEBHOOK"